# Generated by Django 4.2 on 2024-01-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_post_photo_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Events', 'Events'), ('News', 'News')], default='Events', max_length=50),
        ),
    ]
