# Generated by Django 4.2 on 2024-01-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strand',
            field=models.CharField(blank=True, choices=[('tvl', 'TVL'), ('abm', 'ABM'), ('humss', 'HUMSS'), ('stem', 'STEM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_graduated',
            field=models.PositiveIntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
