# Generated by Django 4.2 on 2024-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year_graduated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
