# Generated by Django 4.2 on 2024-01-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year_graduated',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
